service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.bucketName}"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: ${param:SQSArn}

custom:
  bucketName: import-service-rs

functions:
  importProductsFile:
    handler: lambdas/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: lambdas/importFileParser.importFileParser
    events:
      - s3:
          bucket: import-service-rs
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          exisiting: true



